feat: update_user_ext_source
CESNET/satosacontrib.perun pull request #1
Opened 2022-04-28 15:53 UTC by Br3nKo

2022-05-02 10:19 UTC, xpavlic commented
Change PR to draft.

2022-05-13 09:36 UTC, melanger requested changes

2022-05-13 09:36 UTC, melanger commented on microservices/update_user_ext_source.py
> +        self.DEBUG_PREFIX = "update_user_ext_source: "  # ??
does not really matter, you can use e.g. the class name (`UpdateUserExtSource`)

2022-05-13 09:36 UTC, melanger commented on microservices/update_user_ext_source.py
> +            'attributes': data['Attributes'],
```suggestion
            'attributes': data.attributes,

```
in SATOSA it's `data.attributes` (see https://github.com/IdentityPython/SATOSA/blob/1de6a360d52369e01a40d7d0400af20735d7e899/src/satosa/internal.py#L114)

2022-05-13 09:36 UTC, melanger commented on microservices/update_user_ext_source.py
> +            # Not sure if it contains user data or user instance
```suggestion
            'perunUserId': data['attributes'][self.__perun_id_attribute][0],
```
There will be an attribute with configurable name, with perunId as the value (you need to add the configuration parameter in constructor).

2022-05-13 09:36 UTC, melanger commented on microservices/update_user_ext_source.py
> +        except:
try to catch specific exception(s) if possible

2022-05-13 09:36 UTC, melanger commented on microservices/update_user_ext_source.py
> +                raise Exception(
`raise` a specific or custom Exception if possible (so that it can be caught specifically)

2022-05-13 09:36 UTC, melanger commented on microservices/update_user_ext_source.py
> +                # but I was told we will store only id and login
```suggestion
            if not attrs_from_idp[source_idp_attribute][0]:
```
this is the same as `data['attributes'][source_idp_attribute][0]`.

2022-05-13 09:36 UTC, melanger commented on microservices/update_user_ext_source.py
> +                # but I was told we will store only id and login
or, if you want the name of the IdP = the ext source name, that's `data["auth_info"]["issuer"]`, so here it would be `data_to_conversion["auth_info"]["issuer"]`

2022-05-13 09:36 UTC, melanger commented on microservices/update_user_ext_source.py
> +                # but I was told we will store only id and login
I guess you want the ext source name directly to eliminate extra call to API.

2022-05-15 23:17 UTC, xpavlic requested changes

2022-05-15 23:17 UTC, xpavlic commented on microservices/update_user_ext_source.py
> +                raise Exception(
Do we want to use satosa.exception.SATOSAError or any of its subclasses?

2022-05-15 23:17 UTC, xpavlic commented on microservices/update_user_ext_source.py
> +            # use config store to get config which
I think, that whole configuration should be in microservice configuration file. Just add check for default values if any is missing.

2022-05-26 12:34 UTC, xpavlic requested changes

2022-05-26 12:34 UTC, xpavlic commented on microservices/update_user_ext_source.py
> +        self.__adapters_manager = AdaptersManager()
In new version of perun.connector you have to pass global attributes map to AdaptersManager. I added ConfigStore class to utils for this reason. There will be global config, with filepath to global attributes map etc. And every microservice will have path to this global config in its own config. Global means same for all microservices.

2022-05-26 12:34 UTC, xpavlic commented on microservices/update_user_ext_source.py
> +        return config
```suggestion
    def __get_configuration(self):
        config = self.DEFAULT_CONFIG
        for key in config.keys():
            if key not in self.__config:
                logger.warning('%s: %s missing in config. Using default value.' % self.__class__.__name__, key)
            else:
                config[key] = self.__config[key]
        return config
```

2022-05-26 12:34 UTC, xpavlic commented on microservices/update_user_ext_source.py
> +logger = logging.getLogger(__name__)
We can use Logger from perun.connector to keep consistent format.

2022-05-26 12:35 UTC, xpavlic commented
Main branch has been updated. Please rebase.

2022-06-02 13:19 UTC, xpavlic requested changes
Add global_microservices_config.yml to config templates. it can look like this. (I changed some options names, do not forget to update in code).
```
perun_user_id_attr: perunUserId
attrs_cfg_path: filepath
adapters_manager:
  adapters:
    - type: ldap
      #1-X 1 highest
      priority: 1
      username: cn=admin,dc=muni,dc=cz
      base_dn: dc=muni,dc=cz
      password: mypassword
      start_tls: True
      servers:
        - hostname: ldap://openldap
          port: 389
        - hostname: ldap://openldap2
          port: 389

    - type: openApi
      priority: 2
      host: https://perun.cesnet.cz/krb/rpc
      #possible values: BasicAuth, ApiKeyAuth, BearerAuth
      auth_type: BasicAuth
      #BA
      username: username
      password: mypasswd
      #ApiKeyAuth
      api_key: your_api_key
      #BearerAuth
      access_token: your_bearer_token
```

2022-06-02 13:19 UTC, xpavlic commented on microservices/update_user_ext_source.py
> +            utils.ConfigStore.ConfigStore.get_attributes_map(
Missing AdaptersManager config. This config will be also in global microservices config.

2022-06-03 12:13 UTC, Br3nKo commented on microservices/update_user_ext_source.py
> +            utils.ConfigStore.ConfigStore.get_attributes_map(
It was there, but pycharm was not happy with constructor taking more than 1 argument. Now it works, so maybe perun.connector was not locally updated correctly.

2022-06-08 20:08 UTC, xpavlic approved these changes

2022-06-09 10:52 UTC, xpavlic commented
Functionality around attributes in perun.connector will be a bit changed. This will probably need update acording to it.

2022-06-23 12:21 UTC, xpavlic requested changes

2022-06-23 12:21 UTC, xpavlic commented on microservices/update_user_ext_source.py
> +        return attrs_to_update
Also |= does not work for lists only for dicts.

2022-06-29 21:48 UTC, Br3nKo commented on microservices/update_user_ext_source.py
> +                attr_map.keys()
so `attr_map.keys()` ->  attrs_from_idp?

2022-07-01 07:46 UTC, melanger commented on microservices/update_user_ext_source.py
> +            'sourceIdPAttributeKey': 'sourceIdPEntityID',
in SATOSA there is no need to have `sourceIdPAttributeKey`, because the source IdP entity ID is in `data['auth_info']['issuer']`

2022-07-01 07:49 UTC, melanger commented on microservices/update_user_ext_source.py
> +                attr_map.keys()
You don't need `attr_map` (`config["attrMap"]`), because the map is in `attr_map_cfg` (here `self.attr_map_cfg`).

In this microservice's config, there will be RPC names in the other config options and they will be optionally converted using the global `attr_map_cfg`.

2022-07-01 07:51 UTC, melanger commented
@Br3nKo Please add an example config for this microservice.

2022-07-14 10:19 UTC, melanger requested changes

2022-07-14 10:19 UTC, melanger commented on microservices/update_user_ext_source.py
> +                attr = attrs_from_idp[attr_map[attr_name]]
```suggestion
            attr = attrs_from_idp.get(attr_map[attr_name], dict())
```

2022-07-14 10:19 UTC, melanger commented on microservices/update_user_ext_source.py
> +                    attr |= attr_value
```suggestion
                attr |= attr_value.split(';') if attr_name in serialized_attrs else attr_value
```

2022-07-20 10:59 UTC, melanger approved these changes

2022-07-20 11:39 UTC, vyskocilpavel commented on microservices/update_user_ext_source.py
> +                    + str(user_id) + ' and IdP ' + ext_source_name
Change msq to something like:
`No userExtSource found for IDP:<ext_source_name>` and user identifiers: [<user_identifiers>]

User may have more USE from one source, so it's not clear to log only user_id and ext_source_name

2022-07-20 11:39 UTC, vyskocilpavel commented on config_templates/update_user_ext_source.yaml
> +  global_cfg_path: path
What does mean `attribute` in this context? It is a fixed key and `value` is the attribute name?

Or `attribute` means `attribute_name` and value is something other?

Maybe it will be better to create a more complex template configuration because this is not clear to me.

2022-07-20 11:50 UTC, Br3nKo commented on tests/test_update_ues.py
> +  },
That is structure of data for the tests. Since it is not clear to me how exactly the config should look like (hence the following review) I decided to use this structure for the purpose of testing the methods. (I have not found the config to UpdateUserExtSource in confing templates - simplesaml repository)

2022-07-20 11:53 UTC, melanger commented on microservices/update_user_ext_source.py
> +                )
@Br3nKo This check is not needed because `data_to_conversion` is SATOSA's internal structure, which always includes `auth_info` and `issuer`

2022-07-20 11:56 UTC, melanger commented on tests/test_update_ues.py
> +  },
@Br3nKo It can look differently than in PHP, but you need to achieve the same goal and it needs to correspond to the way you read from config in the microservice.

So, if you read `arrayToStringConversion` as a dictionary, it needs to be a dictionary in YAML, both in tests and in example.

2022-07-20 12:25 UTC, vyskocilpavel commented on tests/test_update_ues.py
> +  },
Ok.
Module is configured via authproc filters.
Here is example of configuration for updateUES:
```
'class' => 'perun:UpdateUserExtSource',
                'attrMap' => [
                    'uesCnAttr' => 'cn',
                    'uesDisplayNameAttr' => 'displayName',
                    'uesGivenNameAttr' => 'givenName',
                    'uesSnAttr' => 'sn',
                    'uesOrganizationAttr' => 'o',
                    'uesMailAttr' => 'mail',
                    'uesAffiliationAttr' => 'eduPersonScopedAffiliation',
                    'uesEntitlementAttr' => 'eduPersonEntitlement'
                ],
                'arrayToStringConversion' => [
                    'uesAffiliationAttr',
                    'uesEntitlementAttr'
                ],
                'appendOnlyAttrs' => [
                   'uesEntitlementAttr'
                ],

```

2022-07-28 11:11 UTC, xpavlic requested changes
Add config template for this microservice.

2022-07-28 11:11 UTC, xpavlic commented on satosacontrib/perun/config_templates/global_microservices_config.yaml
> +perun_user_id_attr: perunUserId
Remove this file, it is already in config_templates but with another name.

2022-07-28 11:56 UTC, Br3nKo commented on satosacontrib/perun/config_templates/global_microservices_config.yaml
> +perun_user_id_attr: perunUserId
config was there, probably a mistake during rebase

2022-08-03 08:28 UTC, xpavlic requested changes

2022-08-03 08:28 UTC, xpavlic commented on tests/test_update_ues.py
> +        self.auth_info = None
Remove and use classes from `test_microserivce_loader.py`

2022-08-03 11:22 UTC, xpavlic requested changes

2022-08-03 11:22 UTC, xpavlic commented on satosacontrib/perun/config_templates/update_user_ext_source.yaml
> +module: satosacontrib.perun.micro_services.update_user_ext_source.UpdateUserExtSource
change parameters to snake_case (also in code)

2022-08-03 11:41 UTC, xpavlic requested changes

2022-08-03 11:41 UTC, xpavlic commented on satosacontrib/perun/micro_services/update_user_ext_source.py
> +            'perunUserId': data.attributes[self.__perun_id_attr][0],
```suggestion
            'perunUserId': data.attributes[self.__perun_id_attr],
```

2022-08-04 08:33 UTC, xpavlic requested changes

2022-08-04 08:33 UTC, xpavlic commented on satosacontrib/perun/config_templates/update_user_ext_source.yaml
> +    - uesEntitlementAttr
should be snake_case to match attrs in attr_map

2022-08-04 08:33 UTC, xpavlic commented on satosacontrib/perun/config_templates/update_user_ext_source.yaml
> +    - uesEntitlementAttr
same as above

2022-08-04 08:33 UTC, xpavlic commented on satosacontrib/perun/config_templates/update_user_ext_source.yaml
> +    - eduPersonUniqueId
same

2022-08-04 08:33 UTC, xpavlic commented on tests/test_update_ues.py
> +}
should match config template keys (snake_case update)

2022-08-04 10:35 UTC, xpavlic approved these changes

2022-08-04 10:35 UTC, merged