feat: PerunEnsureMember
CESNET/satosacontrib.perun pull request #10
Opened 2022-07-07 10:16 UTC by Br3nKo

2022-07-07 14:41 UTC, melanger requested changes
please (later) add config example and unit tests

2022-07-07 14:41 UTC, melanger commented on microservices/perun_ensure_member.py
> +            params[PerunConstants.TARGET_EXTENDED] = callback
similar code is in https://github.com/CESNET/satosacontrib.perun/pull/8, please consult with @PeterBolha and extract it into utils

2022-07-24 19:11 UTC, Br3nKo commented
Checks will not be successfull until Utils and PerunConstants are merged

2022-07-25 09:12 UTC, melanger approved these changes

2022-08-03 11:15 UTC, xpavlic requested changes

2022-08-03 11:15 UTC, xpavlic commented on satosacontrib/perun/micro_services/perun_ensure_member.py
> +        self.__handle_user(user, vo, data, context)
We do not save user in data anymore. We just save user_id into attributes. Change user variables to user_id.
```suggestion
        user_id = data.attributes.get(self.__global_cfg["perun_user_id_attribute"])
        if not user_id:
            raise SATOSAError(
                self.LOG_PREFIX + 'Missing mandatory field '
                                  '\'perun.user\' in request. Hint: Did you '
                                  'configured PerunIdentity microservice '
                                  'before this microservice?'
            )
        vo = self.__adapters_manager.get_vo(short_name=self.__vo_short_name)
        if not vo:
            raise SATOSAError(
                self.LOG_PREFIX + 'VO with vo_short_name \''
                + self.__vo_short_name + '\' not found.'
            )

        self.__handle_user(user_id, vo, data, context)
```

2022-08-03 11:15 UTC, xpavlic commented on requirements.txt
> +SATOSA~=8.1.0
revert changes

2022-08-03 11:17 UTC, xpavlic commented
Rebase branch and pipelines will pass, update tests.

2022-08-03 11:23 UTC, xpavlic requested changes

2022-08-03 11:23 UTC, xpavlic commented on satosacontrib/perun/config_templates/perun_ensure_member.yaml
> +module: satosacontrib.perun.micro_services.perun_ensure_member.PerunEnsureMember
change paremters to snake_case (also in code)

2022-08-08 08:02 UTC, xpavlic approved these changes

2022-08-08 08:03 UTC, merged