feat: satosacontrib.perun packages, proxystatistics_microserivce, correct module paths in microservices configs
CESNET/satosacontrib.perun pull request #13
Opened 2022-07-18 12:26 UTC by xpavlic

2022-07-19 12:57 UTC, melanger requested changes

2022-07-19 12:57 UTC, melanger commented on satosacontrib/perun/micro_services/proxystatistics_microservice.py
> +            f'postgresql+psycopg2://{self.stats_user}:{self.stats_password}@mfapgbouncer:6432/{self.stats_db}')
Please make the whole string configurable instead (`mfapgbouncer` and `6432` would need to be options, too, maybe also the `psycopg2` driver, so it is easier to configure the whole string as one option).

2022-07-19 12:57 UTC, melanger commented on setup.py
> +        "SATOSA==8.0.1",
Why exactly 8.0.1? Couldn't it be e.g. `>=8.0.1,<9`?

2022-07-20 07:46 UTC, xpavlic commented on setup.py
> +        "SATOSA==8.0.1",
The version of SATOSA in our docker is 8.0.1. In case there is later version, pip uninstalls older one and installs latest possible and it caused some errors. Also I tried to use 8.1.1 in docker and metadata error occured. So I made it matching.

2022-07-20 09:11 UTC, melanger commented on satosacontrib/perun/micro_services/proxystatistics_microservice.py
> +            f'postgresql+psycopg2://{self.stats_user}:{self.stats_password}@mfapgbouncer:6432/{self.stats_db}')
I meant merge all the database options into a single "database connection string", but this will also work, thanks.

2022-07-20 09:12 UTC, melanger approved these changes
good job, thanks

2022-07-20 09:33 UTC, merged