Added skeleton of get perun user microservice
CESNET/satosacontrib.perun pull request #2
Opened 2022-05-02 08:52 UTC by PeterBolha

2022-05-02 09:00 UTC, melanger requested changes
Use conventional commit message, e.g. "feat: get perun user microservice", and set PR status to Draft

2022-05-02 09:51 UTC, PeterBolha commented
> Use conventional commit message, e.g. "feat: get perun user microservice", and set PR status to Draft

Initially, in AdaptersManager we used a workflow where commits were constantly squashed with each new push so there was always only a commit like "feat: get perun user microservice". Then we switched to keeping temporary history which would be squashed upon merging into main. To my understanding, the conventional commits with standardized labels like _feat_, _fix_ etc. were reserved for squashed, cohesive groups of changes ready to be merged into main. So there could be a group of commits labeled like:

A - Minor change of something
B - Minor tweak of something else
C - Addition of attribute

and if commits A,B and C completed some bit of functionality, they would be squashed into something like:
A - feat: implemented something

Perhaps I misunderstood the workflow earlier. I don't have a problem with labeling everything in the standardized format, I just want to make sure we're all on the same page beforehand. Should the above scenario look like:

A - fix: minor change of something
B - fix: minor tweak of something else
C - feat: addition of attribute

Or should I perhaps keep it to "A - feat: implemented something" at all times and squash before each push?

2022-05-03 09:51 UTC, melanger commented
> > Use conventional commit message, e.g. "feat: get perun user microservice", and set PR status to Draft
> 
> Initially, in AdaptersManager we used a workflow where commits were constantly squashed with each new push so there was always only a commit like "feat: get perun user microservice". Then we switched to keeping temporary history which would be squashed upon merging into main. To my understanding, the conventional commits with standardized labels like _feat_, _fix_ etc. were reserved for squashed, cohesive groups of changes ready to be merged into main. So there could be a group of commits labeled like:
> 
> A - Minor change of something B - Minor tweak of something else C - Addition of attribute
> 
> and if commits A,B and C completed some bit of functionality, they would be squashed into something like: A - feat: implemented something
> 
> Perhaps I misunderstood the workflow earlier. I don't have a problem with labeling everything in the standardized format, I just want to make sure we're all on the same page beforehand. Should the above scenario look like:
> 
> A - fix: minor change of something B - fix: minor tweak of something else C - feat: addition of attribute
> 
> Or should I perhaps keep it to "A - feat: implemented something" at all times and squash before each push?

If A,B,C are just modifications of a single resulting commit (which is probably this case), then I'm fine with the first approach, leave out the prefixes and squash before merge.
If, for example, A+B produce a "feat:" commit but C is a different "fix:", then of course the first approach does not work. That's why I (personally) squash continuously when needed and I create a PR once everything seems ready.

In this case, while the PR is a Draft, you can leave out the prefixes.

2022-05-03 09:57 UTC, melanger requested changes

2022-05-03 09:57 UTC, melanger commented on microservices/perun_user_microservice.py
> +        self.__allowed_requesters = config.get("allowed_requesters")
`config.get("allowed_requesters")` is the same as `config["allowed_requesters"]`. If you want to have an optional parameter, you have to supply a default value, e.g. `config.get("allowed_requesters", [])` or `config.get("allowed_requesters", None)`

2022-05-03 09:57 UTC, melanger commented on microservices/perun_user_microservice.py
> +                # TODO make sure this is how redirect works
Take a look at e.g. https://github.com/CESNET/satosa-microservice-webauthn/blob/c9ae290900cdc128c46d8af8788b1ed251cba93e/webauthn_microservice.py#L89

2022-05-05 06:28 UTC, PeterBolha commented on microservices/perun_user_microservice.py
> +        self.__allowed_requesters = config.get("allowed_requesters")
I think `None` is the default return value for `get()` method on python dict, therefore `config.get("key"`) and `config.get("key", None)` should be equivalent. In perun identity beta, `None` was used as the default value, so I shortened it to `config.get("allowed_requesters")`, but I can keep it explicit if that seems better. Perhaps it's more easily understandable that way.

2022-05-05 06:36 UTC, melanger commented on microservices/perun_user_microservice.py
> +        self.__allowed_requesters = config.get("allowed_requesters")
You're right, `None` is the default default, so `.get()` is different from `[]`.

You might still want to use an empty list instead of None, because then you don't have to branch.

2022-05-05 06:55 UTC, PeterBolha commented on microservices/perun_user_microservice.py
> +            raise SATOSAError(f"Missing key: {missing_key} in config file.")
I think my mistake was rather naming error improperly. I put this except block there because of the line `name = data["auth_info"]["issuer"]`. I'm not sure whether `data` can actually have missing keys, but I put it there just in case. I could rename the error or get rid of the except block altogether.

2022-05-05 06:57 UTC, melanger commented on microservices/perun_user_microservice.py
> +            raise SATOSAError(f"Missing key: {missing_key} in config file.")
[InternalData](https://github.com/IdentityPython/SATOSA/blob/1de6a360d52369e01a40d7d0400af20735d7e899/src/satosa/internal.py#L114) is a call and [AuthenticationInformation](https://github.com/IdentityPython/SATOSA/blob/1de6a360d52369e01a40d7d0400af20735d7e899/src/satosa/internal.py#L82) is a class, the keys cannot be missing, so you don't have to test for this.

2022-05-10 06:57 UTC, PeterBolha commented on microservices/perun_user_microservice.py
> +        self.__allowed_requesters = config.get("allowed_requesters")
Yes, that's a good idea. I'll add `[]` default return values.

2022-05-10 07:01 UTC, PeterBolha commented on microservices/perun_user_microservice.py
> +            raise SATOSAError(f"Missing key: {missing_key} in config file.")
Alright that makes sense, I removed the checking.

2022-05-12 11:50 UTC, xpavlic requested changes

2022-05-12 11:50 UTC, xpavlic commented on utils/jws.py
> +    def _get_api_jwk(self):
remove

2022-05-12 11:50 UTC, xpavlic commented on utils/jws.py
> +        current_timestamp = int(time.time())
```suggestion
```

2022-05-12 11:50 UTC, xpavlic commented on utils/jws.py
> +class RedirectService:
add public static method generate_noonce 

letters = string.ascii_lowercase
actual_time = str(int(time.time()))
rand = random.SystemRandom()
return actual_time + ''.join(rand.choice(letters) for _ in range(54))

2022-05-12 11:50 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +        return super().process(context, data)
You have to register endpoint, and after redirect it will get back into registered method and do another request to check if registration was suceessfull. You can find inspiration in.  [https://github.com/CESNET/satosa-microservice-webauthn/blob/c9ae290900cdc128c46d8af8788b1ed251cba93e/webauthn_microservice.py#L12](satosa-microservice-webauthn). If you need more help with that, let me know.

2022-05-13 09:41 UTC, melanger commented on utils/jws.py
> +        self._CONFIG = config
please use e.g. ECDSA as the default, not RSA (which is considered not as secure and requires much longer keys)

2022-05-16 09:23 UTC, PeterBolha commented on microservices/perun_user_microservice.py
> +        return super().process(context, data)
I'm not sure I understand the process of endpoint registration. In `register_endpoint` method, `_handle_webauthn_response` is called with no given parameter even though this method takes is context parameter which it further uses. It also uses user_id, signing_key and api_url from config. Will we use these attributes as well?

2022-05-16 14:41 UTC, melanger commented on microservices/perun_user_microservice.py
> +        return super().process(context, data)
The endpoint is called after user is redirected back from the external page to SATOSA. If you need any data there, you have to save them into session and recover them after the user gets back. See https://github.com/CESNET/satosa-microservice-webauthn/blob/master/webauthn_microservice.py - there it is called "saved_state".

2022-05-17 06:40 UTC, PeterBolha commented on microservices/perun_user_microservice.py
> +        return super().process(context, data)
So to my understanding, we want to obtain perun user based on their credentials. We sign this request, send it to an external page while saving current user's data in a session. We register an endpoint where the reply from the external website arrives. If the request is not allowed or the reply is somehow invalid, we raise an exception. So the registering of endpoint is not calling the method in any way, it just tells the external website where to reply and the context is supplied from our session?

2022-05-20 13:09 UTC, melanger commented on microservices/perun_user_microservice.py
> +        return super().process(context, data)
> So to my understanding, we want to obtain perun user based on their credentials. We sign this request, send it to an external page while saving current user's data in a session. We register an endpoint where the reply from the external website arrives. If the request is not allowed or the reply is somehow invalid, we raise an exception.

Yes.

> So the registering of endpoint is not calling the method in any way, it just tells the external website where to reply and the context is supplied from our session?

It does not tell the external website, registration of endpoint just creates a URL on the proxy to which the external website (or our separate module) can redirect back to ("reply to"). The registration method is only called once when SATOSA is starting. The method which is registered on the endpoint is called whenever the external website/module redirects user to it, so it needs to read data from the external source and also extract user data (context) from session.

2022-05-20 13:12 UTC, melanger commented on microservices/perun_user_microservice.py
> +        return super().process(context, data)
Check out https://github.com/CESNET/satosa-microservice-webauthn/blob/master/webauthn_microservice.py - the process method makes a redirect to external module, the external module redirects back to the endpoint registered in `register_endpoints`, so the method `_handle_webauthn_response` is called, which gets data from external module (here by backchannel) and extracts user context from session (`saved_state = context.state[self.name]` etc.)

2022-05-23 11:07 UTC, xpavlic requested changes
Rebase your branch, there are few updates in requirements.

2022-05-23 11:07 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +    def _handle_webauthn_response(self, context):
```suggestion
    def _handle_registration_response(self, context):
```

2022-05-23 11:07 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +        jws = JWS(message_json, alg=self.signing_key.alg).sign_compact(
Use method for signing in utils.

2022-06-08 17:38 UTC, xpavlic requested changes

2022-06-08 17:38 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +                # TODO add configurable attribute name for user id
attr name will be in global cfg. Example is above.

2022-06-08 17:38 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +                data.subject_id = user.id
According to perun_identity_beta, data.subject_id should be login which is user attribute and different of user id which we want in attributes.

2022-06-08 17:38 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +                "authn_context_class_ref"]
We need to perform same functionality with registered user as in process to save user data.
```suggestion
```

2022-06-08 17:38 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +                "authn_context_class_ref"]
probably you can call return process(context, internal_response)

2022-06-08 17:38 UTC, xpavlic commented on utils/utils.py
> +    def sign_data(data: dict[str, str], config: dict[str, str] = None) -> str:
I would rather pass parameters like keystore etc. instead of config

2022-06-10 08:19 UTC, PeterBolha commented on microservices/perun_user_microservice.py
> +    def __init__(self, config, *args, **kwargs):
Maybe I'd rename `adapters_manager`  to `adapters_manager_cfg` to be consistent with other config names

2022-06-10 08:39 UTC, PeterBolha commented on microservices/perun_user_microservice.py
> +        except ApiException as api_exception:
I think RPC can do the same thing. Shouldn't we handle it in a same way as the ApiException? From logical standpoint, it's the same scenario.

2022-06-10 09:34 UTC, PeterBolha commented on microservices/perun_user_microservice.py
> +                data.subject_id = user.id
So if I understand it correctly - in `perun_identity_beta` the `login` in `data.subject_id = login` is the entire user extracted by the rpc request?

2022-06-13 07:22 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +                data.subject_id = user.id
Login is value of configurable attribute of user from perun not User object.

2022-06-13 07:26 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +        except ApiException as api_exception:
I will add throwing exceptions from LDAP Adapter with changes in attributes.

2022-06-13 07:28 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +    def __init__(self, config, *args, **kwargs):
In my opinion adapters_manager is ok because there are only configs in this file so it is not needed to write cfg in every option name.

2022-06-13 08:01 UTC, PeterBolha commented on microservices/perun_user_microservice.py
> +    def __init__(self, config, *args, **kwargs):
Alright, that makes sense. I'll keep it like that and add this global config.

2022-06-21 13:49 UTC, xpavlic requested changes

2022-06-21 13:49 UTC, xpavlic commented on config_templates/global.yaml
> +     password: mypassword
add `rp_id_attribute: urn:perun:facility:attribute-def:def:rpIdentifier` as new configuration option.

2022-06-21 13:49 UTC, xpavlic commented on config_templates/global.yaml
> +     access_token: your_bearer_token
add `rp_id_attribute: urn:perun:facility:attribute-def:def:rpIdentifier` as new configuration option.

2022-06-21 13:49 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +        if user is None:
```suggestion
        if not user:
```

2022-06-21 13:49 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +        return Redirect(f"{self.__registration_page_url}/{signed_nonce}/")
```suggestion
        nonce = Utils.generate_nonce()
        request_data = {"nonce": nonce,
                        "time": str(int(time.time()))}
        signed_request_data = self.sign_data(request_data)
        data['nonce'] = nonce
        context.state[self.name] = data.to_dict()
        return Redirect(f"{self.__registration_page_url}/{signed_request_data}")
```

2022-06-21 13:49 UTC, xpavlic commented on utils/utils.py
> +        return signed_data
```suggestion
        return Utils.__get_jwt(data, token_signing_key, token_alg)
```

2022-06-21 13:49 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +        request = f"{self.__api_url}/{signed_message}"
```suggestion
        data = {"nonce": internal_response['nonce'],
                "time": str(int(time.time()))}

        signed_data = self.sign_data(data)
        request = f"{self.__api_url}/{signed_data}"
```

2022-06-21 13:49 UTC, xpavlic commented on microservices/perun_user_microservice.py
> +            raise Exception("Authentication was unsuccessful.")
```suggestion
            raise Exception("Registration was unsuccessful.")
```

2022-06-23 09:52 UTC, xpavlic requested changes

2022-06-23 09:54 UTC, xpavlic commented
After https://github.com/CESNET/perun.connector/pulls will be merged, update perun.connector version.

2022-07-21 10:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/perun_user_microservice.py
> +        self.__perun_login_attribute = global_config["perun_login_attribute"]
Does not match with global config in templates.

2022-07-21 10:46 UTC, xpavlic commented on satosacontrib/perun/utils/Utils.py
> +    def secure_redirect_with_nonce(
In my opinion, we should pass request data as parameter. In some cases we probably want send another informations not only nonce and time. In this microservice you could just pass empty dict and in this method just add nonce and time to it.

2022-07-21 10:48 UTC, xpavlic requested changes

2022-07-21 10:48 UTC, xpavlic commented on requirements.txt
> +pytest~=7.1.2
the . is correct content. We use setup.py to install dependencies.

2022-07-22 07:38 UTC, melanger commented on requirements.txt
> +pytest~=7.1.2
test dependencies have to be separated, something like:
```python
install_requires = [
    'requests',
    ]

tests_require = [
    'freezegun',
    ]

setup(name='satosacontrib.perun',
      # ...
      install_requires=install_requires,
      tests_require=tests_require,
```

But if it was a regular dependency, it would go into `install_requires` in `setup.py`

2022-07-27 13:23 UTC, xpavlic requested changes
Rebase then last thing to change is that AdaptersManager now throws AdaptersManagerException when cannot get entity from adapters.

2022-07-27 13:23 UTC, xpavlic commented on satosacontrib/perun/micro_services/perun_user_microservice.py
> +        self.__registration_page_url = config.get("registration_page", [])
```suggestion
        self.__registration_page_url = config.get("registration_page_url", [])
```

2022-07-27 13:23 UTC, xpavlic commented on satosacontrib/perun/config_templates/perun_user.yaml
> +  registration_url: https://example.com/register/
```suggestion
  registration_page_url: https://example.com/register/
```

2022-07-27 14:15 UTC, xpavlic approved these changes

2022-07-27 14:18 UTC, merged