feat: sp_authorization_microservice
CESNET/satosacontrib.perun pull request #8
Opened 2022-06-21 10:09 UTC by PeterBolha

2022-06-22 08:40 UTC, melanger requested changes

2022-06-22 08:40 UTC, melanger commented on config_templates/sp_authorization.yaml
> +    - handle_unsatisfied_membership: handle_unsatisfied_membership
```suggestion
  filter_config:
    check_group_membership_attr: check_group_membership_attr
    vo_short_names_attr: vo_short_names
    registrar_url: registrar_url
    allow_registration_attr: allow_registration_attr
    registration_link_attr: registration_link_attr
    skip_notification_sps:
      - sp1
      - sp2
      - sp3
    handle_unsatisfied_membership: handle_unsatisfied_membership
```
This is equivalent to:
```json
{
  "filter_config": {
    "check_group_membership_attr": "check_group_membership_attr",
    // ....
    "skip_notification_sps": ["sp1", "sp2", "sp3"]
  }
}
```

2022-06-22 08:43 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +            perun_user_stage = ""  # PerunUser::STAGE
This is not needed, it's just the name of the previous filter/microservice. You can just put "PerunUser" in the message.

2022-06-27 13:22 UTC, melanger requested changes

2022-06-27 13:22 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +                f"required SP EntityID")
This is specific for SimpleSAMLphp and not valid for SATOSA. Here, you have to use `data["auth_info"]["issuer"]` and you can assume it is always set.

2022-06-27 13:22 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +                "processing chain?")
In SATOSA, ~~filters~~ are called microservices and we don't use the term ~~processing chain~~.

2022-06-27 13:22 UTC, melanger commented on utils/PerunConstants.py
> +    SP_METADATA_ENTITYID = 'entityid'
SimpleSAMLphp specific, should be removed

2022-06-29 11:16 UTC, melanger requested changes
Do not add constants that are not used, they can be added later. Please add documentation (comments) for each method, explain briefly what it does, what the parameters mean and what's the output or side effect that happens (e.g. a redirect).

2022-06-29 11:16 UTC, melanger commented on utils/PerunConstants.py
> +    STATE_ID = 'stateId'
this should not be used

2022-06-29 11:16 UTC, melanger commented on utils/PerunConstants.py
> +    SP_ADMINISTRATION_CONTACT = 'administrationContact'
this should not be used

2022-07-04 12:31 UTC, melanger requested changes
Please continue with the TODO items

2022-07-04 12:31 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +        data.attributes[PerunConstants.CONTINUE_FILTER_CONFIG] = self.__config
```suggestion
```
probably not needed

2022-07-04 12:31 UTC, melanger commented on utils/PerunConstants.py
> +    CONTINUE_FILTER_CONFIG = 'continueFilterConfig'
```suggestion
```
probably not needed

2022-07-04 12:31 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +                *non_member_vos_with_reg_form]
```suggestion
        return active_member_vos + expired_member_vos_with_reg_form + non_member_vos_with_reg_form
```

2022-07-04 12:31 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +        non_member_vos_with_reg_form = []
You're right, there is no need to have 3 lists. Actually you can use a single `set()` instead of these lists, because the only usage is this:
```
if not (vo_short_name in vo_short_names_for_registration):
```

2022-07-04 12:31 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +            if not (vo_short_name in vo_short_names_for_registration):
```suggestion
            if vo_short_name not in vo_short_names_for_registration:
```

2022-07-04 12:31 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +        registration_url = ""
In the original version, this is a string from config (here this would be the microservice's config option)

2022-07-13 07:57 UTC, melanger requested changes

2022-07-13 07:57 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +                f"^webauthn{self.__endpoint}$",
not `webauthn`

2022-07-13 07:57 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +        return self.process(context, internal_response)
this should go to a utility class as we discussed

2022-07-13 07:57 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +        self.__STAGE = "perun:SpAuthorization"
not used, not needed

2022-07-13 07:57 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +        self.__DEBUG_PREFIX = self.name
use in all messages

2022-07-13 07:57 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +        sp_entity_id = data.requester
`sp_entity_id` is not 100% correct, because it can also be a `rp_client_id`. I think you can just use `data.requester` directly.

2022-07-13 07:57 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +                                                        self.__check_group_membership_attr] or False  # noqa
```suggestion
        result[self.__CHECK_GROUP_MEMBERSHIP] = facility_attrs.get(self.__check_group_membership_attr, False)
```
shorter, applies to all attributes like this

2022-07-13 08:34 UTC, PeterBolha commented on microservices/sp_authorization_microservice.py
> +        return self.process(context, internal_response)
There's one problem here. We use info from `__signing_cfg` for signing, which is obtained from `__global_config` which is obtained by `ConfigStore` using link from micorservice local config, which is injected upon instantiation. This structure is a bit convoluted but if I understand it correcty, we currently can't access the signing config data in `Utils` as it is a static class with no config. We could probably hardcode it in there, which doesn't seem very good to me or we could make `Utils` non-static and inject the necessary data, which is probably not ideal either but sounds like a better option to me. Otherwise we'll need to keep passing the same set of config data from each microservice wich requires signing into the util.

2022-07-13 08:34 UTC, PeterBolha commented on microservices/sp_authorization_microservice.py
> +        self.__DEBUG_PREFIX = self.name
Our custom logger utilized here should automatically add this prefix and some additional info to logs. I kept this explicit prefix in exceptions, which don't have the automatic prefix.

2022-07-13 08:37 UTC, melanger commented on microservices/sp_authorization_microservice.py
> +        return self.process(context, internal_response)
You can pass `__signing_cfg` as a parameter into a method from Utils, or you can create a new class, e.g. Signer, which won't be static and will accept `__signing_cfg` items in the constructor. But the goal is to keep this kind of code in one place, instead of in each microservice.

2022-07-13 10:18 UTC, PeterBolha commented on microservices/sp_authorization_microservice.py
> +        return self.process(context, internal_response)
I've made needed changes here and uploaded the modified `Utils` with `PerunUser` microservice branch, where it was originally implemented.

2022-08-04 08:46 UTC, Br3nKo commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        if not user:
```suggestion
        user_id = data.attributes.get(self.__global_cfg["perun_user_id_attribute"])
        if not user_id:
```

2022-08-04 08:47 UTC, Br3nKo commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        if not user:
@xpavlic correct me if I am wrong

2022-08-04 08:48 UTC, Br3nKo commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +                f"No facility found for SP '{data_requester}', skipping "
```suggestion
                f"No facility found for '{data_requester}', skipping "
```

2022-08-04 08:49 UTC, Br3nKo commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +                "Could not fetch SP attributes, user will be redirected to "
```suggestion
                "Could not fetch satosa attributes, user will be redirected to "
```

2022-08-08 12:46 UTC, xpavlic requested changes

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +            return
we need to catch exceptions from AdaptersManager

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +            attr_names.append(self.__REGISTRATION_LINK_ATTR)
```suggestion
        if self.__allow_registration_attr:
            attr_names.append(self.__allow_registration_attr)

        if self.__registration_link_attr:
            attr_names.append(self.__registration_link_attr)
```

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        )
```suggestion
        if self.__allow_registration_attr:
            result[self.__ALLOW_REGISTRATION] = facility_attrs.get(
                self.__allow_registration_attr, False
            )

        if self.__registration_link_attr:
            result[self.__REGISTRATION_LINK] = facility_attrs.get(
                self.__registration_link_attr
            )
```

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        user: User,
```suggestion
        user_id: int,
```

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        user: User,
```suggestion
        user_id: int,
```

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        self, user: User, vo_short_names: List[str]
```suggestion
        self, user_id: int, vo_short_names: List[str]
```

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        )
```suggestion
        is_allowed_registration = facility_attributes.get(self.__ALLOW_REGISTRATION, False)
```

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +                continue
try: except:

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +                )
try: except: block is probably needed too

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +            params[PerunConstants.TARGET_EXTENDED] = callback
Don't know about callback yet. We can keep it there and remove later if not needed.

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +    # TODO check if redirect is implemented correctly
```suggestion
```

2022-08-08 12:46 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +    # TODO check if redirect is implemented correctly
```suggestion
```

2022-08-09 09:14 UTC, PeterBolha commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        )
Originally I wrote it like this (directly taken from PHP impl), however the `get` method on dict should fall back on the provided default value. Therefore I think it's not necessary to test whether the key exists.

2022-08-09 09:14 UTC, PeterBolha commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        logger.info("is active")
I think this is covered by our custom logger's prefix.

2022-08-10 10:17 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        logger.info("is active")
Module name is just in prefix. I think it would be better have it in message too. Just "is active" is not intuitive in my opinion.

2022-08-15 10:49 UTC, xpavlic requested changes

2022-08-15 10:49 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        )
```suggestion
        facility = self.__access_adapters_manager(
            self.__adapters_manager.get_facility_by_rp_identifier, data_requester
        )
```

2022-08-15 10:49 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        )
```suggestion
        user_groups = self.__access_adapters_manager(
            self.__adapters_manager.get_users_groups_on_facility, facility, user_id
        )
```

2022-08-15 10:49 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        )
```suggestion
        facility_attrs = self.__access_adapters_manager(
            self.__adapters_manager.get_facility_attributes, facility, attr_names
        )
```

2022-08-15 10:49 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +            )
```suggestion
            vo = self.__access_adapters_manager(
                self.__adapters_manager.get_vo, short_name=vo_short_name
            )
```

2022-08-15 10:49 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +            )
```suggestion
            member_status = self.__access_adapters_manager(
                self.__adapters_manager.get_member_status_by_user_and_vo, user_id, vo
            )
```

2022-08-15 10:49 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +            )
```suggestion
            has_registration_form = self.__access_adapters_manager(
                self.__adapters_manager.has_registration_form_by_vo_short_name, vo_short_name
            )
```

2022-08-15 10:49 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +        )
```suggestion
        sp_groups = self.__access_adapters_manager(
            self.__adapters_manager.get_sp_groups_by_facility, facility
        )
```

2022-08-15 10:49 UTC, xpavlic commented on satosacontrib/perun/micro_services/sp_authorization_microservice.py
> +            )
```suggestion
            has_registration_form = self.__access_adapters_manager(
                self.__adapters_manager.has_registration_form_group, vo_short_name
            )
```

2022-08-16 08:00 UTC, merged